### ISSUE TITLE
📌 Components & Feature todo list

### ISSUE THREAD

**Issue by zyyv** [onu-ui/onu-ui#55]
|Feature Name | Mentioned | Progression（🚧 ✅ 🆕❌ ） |
| :------------: | :--------------------: | :------------: |
| Build production optimization |  #65  | 🚧 |
| Carousel |  #47  | 🚧 |
| Collapse |  #54| ✅ |
| Popup | #59   |✅ |
| Tooltip | #46  | 🚧 |
| Radio | #56  | 🚧 |
| Input |  #41 | 🚧 |
| Dialog |  | 🚧 |
| Switch | #18  |✅ |
| Rate |  #62   |✅ |
| Message | #43  | ✅ |
| Checkbox | #27  | ✅ |
| Avatar |  #17 | ✅ |
| Card | #25  | ✅ |
| Icon |  | ✅ |
| Tag | #39  | ✅ |
| Alert | #32  | ✅ |
| Button | #2 | ✅ |

**Comment by yzh990918** [comment]
@chris-zhu You can pin this issue.

**Comment by yzh990918** [comment]
Dark Mode adaptation：

Component Name | Mentioned | Progression（🚧 ✅ 🆕❌ ）
-- | -- | --
Carousel |  | 🚧
Collapse |  | 🚧
Popup |  | 🚧
Tooltip |  | 🚧
Radio |  | 🚧
Input |  | 🚧
Dialog |   | 🚧
Switch |  | 🚧
Message |  | 🚧
Checkbox |  | 🚧
Avatar |  |🚧
Card |  | ✅
Icon |   | 🚧
Tag |  | 🚧
Alert |  | ✅
Button |  | 🚧

**Comment by yzh990918** [comment]
Some existing problems are sorted out：
- [x] Currently the component library build does not export the declaration related file, I will fix this part.
- [x] At present, the component library only supports on-demand import. The full import test found that there was a problem, and Vue did not successfully register the component library fully.
- [x] The component library provides the props for the ide code. Currently, the props can only be used with volar, but the props cannot be used for possible values, such as type and size.
- [x] Dark mode is not yet compatible.
- [x] Some components mistakenly use the UnoCSS selector and package this part of unmatch.
- [x] Component documentation and global documentation need to be refined.
- [x] Component libraries support theme configuration.
- [x] The component library supports multiple language switching.

**Comment by zhangmo8** [comment]
Maybe need to a Chinese version's docs

**Comment by yzh990918** [comment]
> Maybe need to a Chinese version's docs

Yes, this will be an important task in our next plan.

**Comment by yzh990918** [comment]
See details of the next step: https://github.com/onu-ui/onu-ui/discussions/64.

**Comment by Tauromachian** [comment]
@yzh990918 I can help with either the radio, input or carousel. UI wise I would have to see what you want of them though.

**Comment by yzh990918** [comment]
> @yzh990918 I can help with either the radio, input or carousel. UI wise I would have to see what you want of them though.

Thanks for the reply, the update of onu is going to be put on hold for a while, and I have been busy looking for a job recently.If you have good suggestions, welcome PR ❤️
